remote_theme: mmistakes/minimal-mistakes@4.24.0
title: T. Selva - AI/ML Portfolio
description: Portfolio of AI/ML projects by T. Selva, showcasing computer vision and data science.
url: "https://tselva-AIML.github.io"
author:
  name: T. Selva
  email: your.email@example.com
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
seo:
  description: AI/ML portfolio by T. Selva, featuring computer vision and data science projects.
  keywords: AI, Machine Learning, Computer Vision, TensorFlow, Keras
include:
  - _pages
collections:
  projects:
    output: true
    permalink: /projects/:path/
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
minimal_mistakes_skin: "mint"
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: GitHub
    url: https://github.com/tselva-AIML/AI-ML-Portfolio
  - title: LinkedIn
    url: https://linkedin.com/in/yourprofile
