remote_theme: mmistakes/minimal-mistakes@4.24.0
title: Selvakumar Thirumalainambi
description: AI/ML portfolio showcasing computer vision and data science projects.
url: "https://tselva-AIML.github.io"
author:
  name: Selvakumar Thirumalainambi
  email: tselva@gmail.com
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
seo:
  description: AI/ML portfolio by Selvakumar Thirumalainambi, featuring computer vision and data science projects.
  keywords: AI, Machine Learning, Computer Vision, TensorFlow, Keras
include:
  - _pages
collections:
  projects:
    output: true
    permalink: /projects/:path/
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: default
minimal_mistakes_skin: "mint"
header:
  nav:
    - title: Home
      url: /
    - title: Projects
      url: /projects/
    - title: About
      url: /about/
    - title: GitHub
      url: https://github.com/tselva-AIML/AI-ML-Portfolio
    - title: LinkedIn
      url: https://www.linkedin.com/in/selvakumar-thirumalainambi
# Disable Recent Posts on homepage
home:
  archive:
    show: false
