name: Jekyll Build and Deploy to GitHub Pages

on:
  push:
    branches: [main] # Or your main branch name (e.g., master)
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x' # Or your preferred Ruby version

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build with Jekyll
        run: bundle exec jekyll build --config _config.yml

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
